services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
  app:
    image: wesleyarizio/mks_code_challenge-app:latest
    environment:
      - PORT=$PORT
      - JWT_SECRET=$JWT_SECRET
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $PORT:8080
    depends_on:
      - postgres
      